### ISSUE TITLE
Subject variable for waiting list subscriptions

### ISSUE THREAD

**Issue by Kahmoon** [codefog/contao-events_subscriptions#32]
Hi Kamil,

it would be very nice if you could mark registrations for the waiting list in the mails with a corresponding subject. Unfortunately, I don't find anything about this in the documentation.

Maybe a complete separate notification center option?

Greetings Frank

**Comment by Kahmoon** [comment]
There should also be an own notification when somebody changes from waiting list to subscribed. I testet this with some of our students and there is no notification when they move up.

If this is a pay enhancement please let me know. We need this :)

Frank

**Comment by Kahmoon** [comment]
I just answered your mail. You can do this enhancement.

The following changes i did to my templates that subscribe button says "set me on waiting list".

therefore i added two language variables in defeault.php

`
$GLOBALS['TL_LANG']['MSC']['events_subscriptions.subscribeWaitinglist']             = 'Auf die Warteliste setzen';
$GLOBALS['TL_LANG']['MSC']['events_subscriptions.unsubscribeWaitinglist']             = 'Von der Warteliste abmelden';
`


I also change the eventsubsription_form.html5 to set the new button labels. Maybe there is a better way

`
        <?php if ($type['form']): ?>
            <form id="<?= $type['form']->formId ?>" action="<?= $type['form']->action ?>" method="<?= $type['form']->method ?>" enctype="<?= $type['form']->enctype ?>">
                <?= $type['form']->hidden ?>
                <?= $type['form']->fields ?>
				
				
				<div class="submit_container">
					
				
				
        		<?php if ($this->subscriptionMaximum - count($this->subscribers['subscribers']) <= 0 && $this->subscription_waitingList): ?>
        			<button type="submit" class="submit <?php if ($type['canUnsubscribe']): ?>unsubscribe<?php else: ?>subscribe<?php endif; ?>">
                    	<?= $type['canUnsubscribe'] ? $GLOBALS['TL_LANG']['MSC']['events_subscriptions.unsubscribeWaitinglist'] : $GLOBALS['TL_LANG']['MSC']['events_subscriptions.subscribeWaitinglist'] ?>
                    </button>
        		<?php else: ?>
                    <button type="submit" class="submit <?php if ($type['canUnsubscribe']): ?>unsubscribe<?php else: ?>subscribe<?php endif; ?>">
                    	<?= $type['canUnsubscribe'] ? $GLOBALS['TL_LANG']['MSC']['events_subscriptions.unsubscribe'] : $GLOBALS['TL_LANG']['MSC']['events_subscriptions.subscribe'] ?>
                    </button>	
        		<?php endif; ?>

                </div>
            </form>
        <?php endif; ?>
`

**Comment by qzminski** [comment]
> There should be two new notifications:
> 1. Event Subscribe: Custom mail on subscribing event on waiting list or just a variable which could be used for custom subject.

This should be already the case using `subscription_waitingList` token.

**Comment by Kahmoon** [comment]
Yep, this is working. Thx

For the button labels there should be a variable to check if the user is actually subscribed or on waiting list.

**Comment by qzminski** [comment]
@Kahmoon this should be fixed on the develop branch already 👍🏻 You can test the new subscription type there as well, more info in the docs: https://github.com/codefog/contao-events_subscriptions/blob/develop/docs/06-notifications.md#notification-types-and-their-purposes

**Comment by qzminski** [comment]
> For the button labels there should be a variable to check if the user is actually subscribed or on waiting list.

This one should also be on `develop` branch now :+1: You can use `$this->subscribeWaitingList` template variable as a helper.

**Comment by Kahmoon** [comment]
How can i install develop versions? Actually i have no testing system. I literally testing on live server ;)

**Comment by qzminski** [comment]
In your Contao Manager you have to change the extension version to be `dev-develop@dev` and then save the changes / update the deps. I highly recommend doing that on some dev system though, can be even a local setup.

**Comment by Kahmoon** [comment]
Ok, i created a test installation. What do i have to change to install dev versions?

```
{
    "name": "contao/managed-edition",
    "type": "project",
    "description": "Contao Open Source CMS",
    "license": "LGPL-3.0-or-later",
    "authors": [
        {
            "name": "Leo Feyer",
            "homepage": "https://github.com/leofeyer"
        }
    ],
    "require": {
        "php": "^7.1",
        "codefog/contao-events_subscriptions": "^2.4",
        "contao-bootstrap/core": "^2.0",
        "contao-bootstrap/form": "^2.1",
        "contao-bootstrap/grid": "^2.0",
        "contao-bootstrap/layout": "^2.0",
        "contao-bootstrap/navbar": "^2.1",
        "contao/calendar-bundle": "^4.6",
        "contao/comments-bundle": "^4.6",
        "contao/conflicts": "*@dev",
        "contao/faq-bundle": "^4.6",
        "contao/listing-bundle": "^4.6",
        "contao/manager-bundle": "4.8.*",
        "contao/news-bundle": "^4.6",
        "contao/newsletter-bundle": "^4.6",
        "dklemmt/contao_dk_mmenu": "^3.0",
        "heimrichhannot/contao-teaser-bundle": "^0.3.2",
        "jrgregory/m17-sticky-backend-footer": "^2.0"
    },
    "config": {
        "component-dir": "assets"
    },
    "extra": {
        "branch-alias": {
            "dev-4.5": "4.5.x-dev"
        }
    },
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
    }
}
```

**Comment by qzminski** [comment]
You have to update it as follows:

```diff
{
    "name": "contao/managed-edition",
    "type": "project",
    "description": "Contao Open Source CMS",
    "license": "LGPL-3.0-or-later",
    "authors": [
        {
            "name": "Leo Feyer",
            "homepage": "https://github.com/leofeyer"
        }
    ],
    "require": {
        "php": "^7.1",
-       "codefog/contao-events_subscriptions": "^2.4",
+       "codefog/contao-events_subscriptions": "dev-develop@dev",
        "contao-bootstrap/core": "^2.0",
        "contao-bootstrap/form": "^2.1",
        "contao-bootstrap/grid": "^2.0",
        "contao-bootstrap/layout": "^2.0",
        "contao-bootstrap/navbar": "^2.1",
        "contao/calendar-bundle": "^4.6",
        "contao/comments-bundle": "^4.6",
        "contao/conflicts": "*@dev",
        "contao/faq-bundle": "^4.6",
        "contao/listing-bundle": "^4.6",
        "contao/manager-bundle": "4.8.*",
        "contao/news-bundle": "^4.6",
        "contao/newsletter-bundle": "^4.6",
        "dklemmt/contao_dk_mmenu": "^3.0",
        "heimrichhannot/contao-teaser-bundle": "^0.3.2",
        "jrgregory/m17-sticky-backend-footer": "^2.0"
    },
    "config": {
        "component-dir": "assets"
    },
    "extra": {
        "branch-alias": {
            "dev-4.5": "4.5.x-dev"
        }
    },
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
    }
}
```

**Comment by Kahmoon** [comment]
Testing looks fine so far.

I get an error in the following scenario:

i changed my slot from waiting list to subscribers -> new notification is send -> everything is fine. When i now try to unsubscribe i get an error:

> 

in AbstractSubscription.php line 86
--
at AbstractSubscription->isOnWaitingList()in NotificationListener.php line 76
at NotificationListener->getWaitingListPromotedSubscription(object(UnsubscribeEvent))in NotificationListener.php line 62
at NotificationListener->onUnsubscribe(object(UnsubscribeEvent))
at call_user_func(array(object(NotificationListener), 'onUnsubscribe'), object(UnsubscribeEvent))in EventDispatcher.php line 36
at EventDispatcher->dispatch('eventsSubscriptions_onUnsubscribe', object(UnsubscribeEvent))in Subscriber.php line 105
at Subscriber->unsubscribe(object(EventConfig), object(MemberSubscription))in MemberSubscription.php line 159
at MemberSubscription->processForm(object(Form), object(EventConfig))in SubscriptionTrait.php line 56

**Comment by qzminski** [comment]
> When i now try to unsubscribe i get an error and unsubscribemail is sent anyways, event the user is not removed from event:

Do you unsubscribe in frontend or backend?

**Comment by Kahmoon** [comment]
i unsubcribe in frontend, sorry

**Comment by qzminski** [comment]
I fixed that issue in 2afc0ca. Please update your dependencies in about 5 minutes and test again 🙂

**Comment by Kahmoon** [comment]
No more errors in this scenario. thx

**Comment by Kahmoon** [comment]
Actually the variable $this->subscription_waitingList has no value. Even if i am on waitinglist or not. Its always empty

`#<?php echo $this->subscription_waitingList; ?>#`

**Comment by qzminski** [comment]
It is not `$this->subscription_waitingList` but `$this->subscribeWaitingList`.

**Comment by Kahmoon** [comment]
Ahh ok. Documentation says

> subscription_waitingList

True if the subscriber is on the waiting list, false otherwise.

**Comment by qzminski** [comment]
Where does it say that? It only says that:

```php
$this->subscription_waitingList; // 1 – waiting list enabled; 0 – disabled
```

https://github.com/codefog/contao-events_subscriptions/blob/master/docs/05-frontend-modules.md#note-on-event_-template

**Comment by Kahmoon** [comment]
Yep, but this variable i always unset in template $this->subscription_waitingList;

$this->subscribeWaitingList is working fine

**Comment by Kahmoon** [comment]
I think i missunderstood the variable. Its a global flag if waiting list is active at all :-P. 

Which variable could i use to switch the button labels. Is there a variable which says "the actual user is on waiting list or not"?

**Button label "Set me on waiting list" on:**
- Waiting list enabled at all ($this->subscribeWaitingList)
- Im not on waiting list on my own

**Button label "remove me from waiting list":**
- Waiting list enabled at all ($this->subscribeWaitingList)
- I am subscribed on the waiting list

**Comment by qzminski** [comment]
@Kahmoon hm that would be possible but only for the logged in members. Please update your dependencies and adjust the following lines in your `eventsubscription_form.html5` template: https://github.com/codefog/contao-events_subscriptions/blob/a810f9c2fa438c1ea2105b2db99942325553f275/templates/partials/eventsubscription_form.html5#L28-L34

**Comment by Kahmoon** [comment]
In my case i just have members who can subscribe. 

You had a small misstype in your snipped. For unsubsribe its the variable $GLOBALS['TL_LANG']['MSC']['events_subscriptions.**un**subscribeWaitingList']

**i tried your snipped but it doesn´t work correctly**

- Event with two slots + 1 waiting list slot = button label "subscribe" (correct)
- 1 dummy + me subscribed = button label "set me on waiting list" (not correct because i am already subscribed)
- 2 dummys subscribed = button label "set me on waiting list" (correct - i am not one the subscribers)
- 2 dummys subscribe + me on waiting list. when i remove 1 dummy via backend my own account moves from waiting list to subscribers = button label for unsibscribing "remove me from waiting list (not correct - should be a regular unsibscribe)

**Comment by Kahmoon** [comment]
Ok, i think i just found the error. it was changed variables in your snipped - section unsibscribe. With this one it works properly

```
				<div class="submit_container">
				    <?php if ($type['canSubscribe']): ?> 
        				<button type="submit" class="submit subscribe btn btn-primary"><?= $this->subscribeWaitingList ? $GLOBALS['TL_LANG']['MSC']['events_subscriptions.subscribeWaitingList'] : $GLOBALS['TL_LANG']['MSC']['events_subscriptions.subscribe'] ?></button> 
     
    				<?php elseif ($type['canUnsubscribe']): ?> 
        				<button type="submit" class="submit unsubscribe btn btn-danger"><?= $type['isOnWaitingList'] ? $GLOBALS['TL_LANG']['MSC']['events_subscriptions.unsubscribeWaitingList'] : $GLOBALS['TL_LANG']['MSC']['events_subscriptions.unsubscribe'] ?></button> 
    				<?php endif; ?> 
				 </div> 
```

**Comment by qzminski** [comment]
Ah good catch, I fixed it in fb4059c. Is all good now?

**Comment by Kahmoon** [comment]
In default settings yes. When i overwrite settings in an event itself, there is a problem

**Global Archive Settings 2 slots, 2 slots waiting list**
- overwriting settings in event: number of waiting list 10 -> $this->subscription_waitingListLimit shows 10 in template (correct)
- disabling overwrite settings in event, $this->subscription_waitingListLimit still shows 10 even it should be reset to 2 from archive settings (incorrect)

When changing the max number of free regular slots in an event when people are already on waiting also works fine. They automatically become normal subscribers but in this case there is no notification sent. This is probably impossible right?

**Comment by qzminski** [comment]
Okay once you will update the dependencies you should be able to use `$this-> subscriptionWaitingListLimit` instead of `$this-> subscription_waitingListLimit `.

> When changing the max number of free regular slots in an event when people are already on waiting also works fine. They automatically become normal subscribers but in this case there is no notification sent. This is probably impossible right?

Not only it would be difficult to do, but it's not a really safe solution I think.

**Comment by Kahmoon** [comment]
Thanks. I cannot find any errors

**Comment by qzminski** [comment]
I have just released 2.5.0 so you can update your composer.json back to the correct shape and update the deps:

```diff
{
    "name": "contao/managed-edition",
    "type": "project",
    "description": "Contao Open Source CMS",
    "license": "LGPL-3.0-or-later",
    "authors": [
        {
            "name": "Leo Feyer",
            "homepage": "https://github.com/leofeyer"
        }
    ],
    "require": {
        "php": "^7.1",
-       "codefog/contao-events_subscriptions": "dev-develop@dev",
+       "codefog/contao-events_subscriptions": "^2.5",
        "contao-bootstrap/core": "^2.0",
        "contao-bootstrap/form": "^2.1",
        "contao-bootstrap/grid": "^2.0",
        "contao-bootstrap/layout": "^2.0",
        "contao-bootstrap/navbar": "^2.1",
        "contao/calendar-bundle": "^4.6",
        "contao/comments-bundle": "^4.6",
        "contao/conflicts": "*@dev",
        "contao/faq-bundle": "^4.6",
        "contao/listing-bundle": "^4.6",
        "contao/manager-bundle": "4.8.*",
        "contao/news-bundle": "^4.6",
        "contao/newsletter-bundle": "^4.6",
        "dklemmt/contao_dk_mmenu": "^3.0",
        "heimrichhannot/contao-teaser-bundle": "^0.3.2",
        "jrgregory/m17-sticky-backend-footer": "^2.0"
    },
    "config": {
        "component-dir": "assets"
    },
    "extra": {
        "branch-alias": {
            "dev-4.5": "4.5.x-dev"
        }
    },
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
    }
}
```

**Comment by Kahmoon** [comment]
Thanks. One thing i missed until yet...sorry

People on Waitinglist should not get the event mail reminder until they move to the subscriber list. 

This also means that notify option next to subscribe button should also be hidden.

**Comment by qzminski** [comment]
> People on Waitinglist should not get the event mail reminder until they move to the subscriber list. Otherwise they get "spammed" even they cannot participate until they move from waiting list to subscribers.

Implemented in 0a4a44f. I'd be glad if you can test that using the same composer.json adjustments like before.

> This also means that notify option next to subscribe button should also be hidden. But this can be done via template.

Are you sure? In such case they will not receive a reminder if they move up from waiting list to subscriber list either.

**Comment by qzminski** [comment]
Ah, forgot to mention – after you update the dependencies make sure to update the database. Then in the calendar settings you will find a new checkbox that allows to disable the reminders for waiting list subscribers.

**Comment by Kahmoon** [comment]
Thanks. Default now is "no notifications for people on waitiling list" correct? The new checkbox will change that they get mails even they are just on the waiting list.

Nah not sure about that....it should be active as they move from waiting list to subscribes. Maybe i just hide it via template when $type['isOnWaitingList'] is true.

**Comment by qzminski** [comment]
If checkbox is unchecked, everybody gets a notification. If checkbox is checked, the waiting list subscribers do not get a notification.

**Comment by Kahmoon** [comment]
OK, thats fine. Can i set this checkbox default via config? No notification for waiting list asdefault makes more sense imho.

 

After extension update i get two frontend errors (Module event reader & event list). Backend is fine

```
(2/2) InternalServerErrorHttpException
The event reader ID 6 has no calendars specified.
```

But there is a calendar specified. There wasn´t changed anything

**Comment by qzminski** [comment]
> OK, thats fine. Can i set this checkbox default via config? No notification for waiting list as default makes more sense imho.

I suggest that you add the following lines to the `/app/Resources/contao/dca/tl_calendar.php` file:

```php
<?php

$GLOBALS['TL_DCA']['tl_calendar']['fields']['subscription_skipWaitingListReminders']['default'] = 1;
$GLOBALS['TL_DCA']['tl_calendar']['fields']['subscription_skipWaitingListReminders']['sql'] = "char(1) NOT NULL default '1'";
```

… rebuild the internal cache and update the database. That might not work for the existing records but in such case just run a SQL query in your favorite MySQL client such as phpMyAdmin:

```sql
UPDATE tl_calendar SET subscription_skipWaitingListReminders='1' WHERE subscription_reminders='1';
```

> After extension update i get two frontend errors (Module event reader & event list). Backend is fine

Are you sure you didn't change anything? Maybe you dropped some columns? There was no change in the code related to those and the extension works fine for me locally.

**Comment by Kahmoon** [comment]
Thanks. I think it should be

`WHERE subscription_reminders='0';`

I didn´t touch my installation after the last testing. But it was a rights thing....the calendar was protected so without login there was "no calender" to show ;)

I just set an event to test the notifications. I will give you feedback.

**Comment by qzminski** [comment]
> Thanks. I think it should be
> WHERE subscription_reminders='0';

Well you can also remove `WHERE` part completely if you want to update ALL calendars. My query updates the calendars that have reminders enabled.

**Comment by Kahmoon** [comment]
OK. Thanks

**Comment by Kahmoon** [comment]
Testuser on waiting list did not get a mail. Perfect. Thx

**Comment by qzminski** [comment]
Great, then you can update composer.json to `"codefog/contao-events_subscriptions": "^2.6"` and update the deps :+1:
